# Generated by Django 6.1 on 2026-08-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='thema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ausgaben', to='pool.thema'),
            preserve_default=False,
        ),
    ]
